from pydantic import BaseModel


# ── Re-used from Agent 2 JSON ─────────────────────────────────────────────────

class Metadata(BaseModel):
    arquivo_origem: str
    data_processamento: str
    modelo_usado: str


class Persona(BaseModel):
    id: str
    nome: str
    papel: str
    caracteristicas: list[str]
    contexto: str
    trechos_relevantes: list[str]


class PersonaAnalysis(BaseModel):
    personas: list[Persona]
    resumo_conversa: str
    tipo_interacao: str


class Story(BaseModel):
    id: str
    historia: str
    prioridade: str
    contexto: str
    trecho_base: str


class PersonaStories(BaseModel):
    persona_id: str
    persona_nome: str
    historias: list[Story]


class UserStoriesSection(BaseModel):
    user_stories: list[PersonaStories]


class Agent2Output(BaseModel):
    metadata: Metadata
    analise_personas: PersonaAnalysis
    historias_usuario: UserStoriesSection


# ── Domain model (generated by Agent 4) ──────────────────────────────────────

class DomainAttribute(BaseModel):
    name: str
    type: str


class DomainRelationship(BaseModel):
    from_entity: str
    to_entity: str
    label: str
    cardinality: str


class DomainEntity(BaseModel):
    name: str
    attributes: list[DomainAttribute]
    methods: list[str]


class DomainModel(BaseModel):
    entities: list[DomainEntity]
    relationships: list[DomainRelationship]
    plantuml_source: str
    image_path: str | None = None


# ── Final consolidated document ───────────────────────────────────────────────

class FinalDocument(BaseModel):
    metadata: Metadata
    conversation_summary: str
    interaction_type: str
    personas: list[Persona]
    domain_model: DomainModel
    srs_markdown_path: str | None = None   # path to Agent 3 .md, embedded in final doc
    srs_content: str | None = None         # raw content of Agent 3 .md
